spring.application.name=ms-order

server.port=${LPORT:10000}

spring.config.import=configserver:http://127.0.0.1:8888

management.endpoints.web.exposure.include=*
management.endpoint.env.show-values=always
management.info.env.enabled=true
management.info.process.enabled=true

management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

info.deneme.xyz=o10
info.deneme.abc=h100
info.deneme.version=@project.version@



