a.b.c=deneme
app.deneme.text1=osman
app.deneme.text2=ali
app.db.username=osman
app.db.password={cipher}a7e506243675ba47cb7fa9fed8a16942e380c4188a485110428c2e3cb560fc80
app.db.url=xyz

eureka.client.service-url.defaultZone=http://127.0.0.1:5555/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.healthcheck.enabled=true

eureka.instance.prefer-ip-address=true